services:
  mysql:
    image: mysql:8.0
    container_name: obras_insumos_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: obras_insumos_db
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/sql_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/sql_seeds.sql:/docker-entrypoint-initdb.d/02-seeds.sql:ro
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obras_insumos_api
    restart: unless-stopped
    ports:
      - '4000:4000'
      - '51212:51212' # Prisma Studio
      - '5555:5555' # Prisma Studio
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/obras_insumos_db
      PORT: 4000
      NODE_ENV: development
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: yarn dev

volumes:
  mysql_data:
